# SPDX-FileCopyrightText: Copyright (c) 2021-2022 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: LicenseRef-NvidiaProprietary
#
# NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
# property and proprietary rights in and to this material, related
# documentation and any modifications thereto. Any use, reproduction,
# disclosure or distribution of this material and related documentation
# without an express license agreement from NVIDIA CORPORATION or
# its affiliates is strictly prohibited.

name: eg3d
channels:
  - pytorch
  - nvidia
dependencies:
  - python >= 3.8
  - pip
  - numpy
  - click
  - pillow
  - scipy
  - pytorch=1.12.1
  - cudatoolkit=11.3
  - requests
  - tqdm
  - ninja=1.10.2
  - matplotlib
  - imageio
  - pip:
    - imgui
    - glfw
    - pyopengl
    - imageio-ffmpeg
    - pyspng
    - psutil
    - mrcfile
    - tensorboard